In [15]:
import tensorflow as tf

# Create TensorFlow object called tensor
#Constants
c = tf.constant("I am a Constant");

#Ways to for imput values dynamically
x = tf.placeholder(tf.string)
y = tf.placeholder(tf.int32)
z = tf.placeholder(tf.float32)

n_features = 120
n_labels = 5

#you can use tf.Variable if you want to be able to modify tensors during execution.. variables should have a default intial value
weights = tf.Variable(tf.truncated_normal((n_features, n_labels)))

n_labels = 5
bias = tf.Variable(tf.zeros(n_labels))

logit_data = [2.0, 1.0, 0.1]
logits = tf.placeholder(tf.float32)

#softmax is a popular activation function that can take any logical scores(logits) from linear regression calculations and convert them into probabilities
softmax = tf.nn.softmax(logits)

#It is a lazy, yet efficient approach to take a logistic classifier function and make it non-linear. The ReLU function is 0 for negative inputs and xfor all inputs x>0. It is defined as f(x) = max(0, x). The function returns 0 if x is negative, otherwise it returns x. 
relu = tf.nn.relu(logits)

#tf.truncated_normal is a great way to generate test data with required shapes, mean and standard deviations
#In this example, i am creating a weights of depth 6 with width 3, height 3 and channels 1
conv1_W = tf.Variable(tf.truncated_normal(shape=(3, 3, 1, 6), mean = 0, stddev = 0.1))

#this step need to be run in the session before you can use any tensor variables
init = tf.global_variables_initializer()

#In tensorflow, everything is executed with in a session
with tf.Session() as sess:
    # Run the tf.constant operation in the session
    constant_output = sess.run(c)
    print(constant_output)
    
    #feed_dict is how you input values into placeholder tensors
    x_output = sess.run(x, feed_dict={x: 'Hello World', y: 1, z: 3.0})
    print(x_output)
    y_output = sess.run(y, feed_dict={x: 'Hello World', y: 1, z: 3.0})
    print(y_output)
    z_output = sess.run(z, feed_dict={x: 'Hello World', y: 1, z: 3.0})
    print(z_output)

    #tf.add, tf.mul are common arithmetic operations you can perform on tensors
    add_output = sess.run(tf.add(y_output, z_output))
    
    #this is needed to be able to use variable tensors in tensor flow
    sess.run(init)

    output = sess.run(conv1_W)

    print(output)

b'I am a Constant'
Hello World
1
3.0
[[[[-0.02945829  0.13463578  0.06254795  0.04890206 -0.02589542  0.06478899]]

  [[-0.05183497 -0.02789631  0.08135591  0.00724334 -0.08392275  0.02622166]]

  [[-0.10023302 -0.10289311  0.18268339  0.00656681 -0.03350198 -0.10188857]]]


 [[[-0.04782532  0.09260066 -0.04645075 -0.00339175 -0.02724966  0.05931205]]

  [[ 0.05827846 -0.13669437  0.1742904   0.0873969   0.1628987  -0.07065492]]

  [[-0.04197415 -0.12577841  0.0335924  -0.12857528  0.17111507  0.07180569]]]


 [[[-0.00154802 -0.01551639  0.01230738 -0.09420497 -0.13994551  0.01997991]]

  [[ 0.09342559 -0.12737565  0.01502761 -0.00285982 -0.0794641   0.02822481]]

  [[-0.00481926 -0.02979227 -0.05099807 -0.09731366 -0.00093376 -0.02866908]]]]
